spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce_auth?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: ${MYSQL_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:your-email@gmail.com}
    password: ${MAIL_PASSWORD:your-app-password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

  jackson:
    default-property-inclusion: non_null

server:
  port: 8081

app:
  jwt:
    secret: ${JWT_SECRET:3MCY9HY0KPxN4w6J+Za3qd+FjcXIBIF1R9/NK1kDsxsfrynJKQXhC1msiEOTWSQ+}
    expiration-ms: ${JWT_EXPIRATION_MS:3600000}

logging:
  level:
    org.springframework.security: INFO